{% set name = "daemonize" %}
{% set version = "2.5.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: dd026e4ff8d22cb016ed2130bc738b7d4b1da597ef93c074d2adb9e4dea08bc3

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  home: "https://github.com/thesharp/daemonize"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Library to enable your code run as a daemon process on Unix-like systems."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
