{% set name = "negspy" %}
{% set version = "0.2.24" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/pkerpedjiev/negspy.git
  git_rev: "a3a0046170548ccac44aa5b09faf3bcc37d5ce39"

build:
  number: 0
  script: "$PYTHON -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - numpy
  run:
    - python
    - numpy

about:
  home: https://github.com/pkerpedjiev/negspy/
  summary: Python NGS Repository
  dev_url: https://github.com/pkerpedjiev/negspy/
