{% set name = "negspy" %}
{% set version = "0.2.24" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/pkerpedjiev/negspy.git
  git_rev: {{ version }}

build:
  number: 0
  script: "$PYTHON -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - numpy
  run:
    - numpy

about:
  home: https://github.com/pkerpedjiev/negspy/
  license_file: LICENSE
  summary: Python NGS Repository
  dev_url: https://github.com/pkerpedjiev/negspy/
