{% set name = "simple-httpfs" %}
{% set version = "0.2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/higlass/simple-httpfs.git
  git_rev: "v{{ version }}"

build:
  number: 0
  entry_points:
    - simple-httpfs=simple_httpfs.__main__:main
  script: "$PYTHON -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python
    - fusepy
    - requests
    - diskcache
  run:
    - python
    - fusepy
    - requests
    - diskcache

about:
  home: http://github.com/higlass/simple-httpfs/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple FUSE-based http file system. Read http files as if they were on the local filesystem.
  dev_url: http://github.com/higlass/simple-httpfs/
