{% set name = "pymacaroons" %}
{% set version = "0.13.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 1e6bba42a5f66c245adf38a5a4006a99dcc06a0703786ea636098667d42903b8

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - pynacl >=1.1.2,<2.0
    - python
    - six >=1.8.0
  run:
    - pynacl >=1.1.2,<2.0
    - python
    - six >=1.8.0

test:
  imports:
    - pymacaroons
    - pymacaroons.binders
    - pymacaroons.caveat_delegates
    - pymacaroons.field_encryptors
    - pymacaroons.serializers

about:
  home: "https://github.com/ecordell/pymacaroons"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Macaroon library for Python"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
