{% set name = "clodius" %}
{% set version = "0.14.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 577067cb62b83d1d733e781677181098d00792838e18459b28a78add74e0d5ab

build:
  number: 0
  entry_points:
    - clodius = clodius.cli.aggregate:cli
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - click >=7
    - cooler >=0.8.5
    - dask
    - h5py
    - negspy
    - nose
    - numpy
    - pandas
    - pip
    - pybbi >=0.2.0
    - pysam
    - python
    - requests
    - slugid
    - sortedcontainers
  run:
    - click >=7
    - cooler >=0.8.5
    - dask
    - h5py
    - negspy
    - nose
    - numpy
    - pandas
    - pybbi >=0.2.0
    - pysam
    - python
    - requests
    - slugid
    - sortedcontainers

test:
  imports:
    - clodius
    - clodius.cli
    - clodius.tiles
  commands:
    - clodius --help

about:
  home: http://github.com/higlass/clodius/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Clodius is a tool for breaking up large data sets into smaller tiles that can subsequently be displayed using an appropriate viewer.
  dev_url: http://github.com/higlass/clodius

extra:
  recipe-maintainers:
    - jrhawley
