{% set name = "slugid" %}
{% set version = "2.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/taskcluster/slugid.py.git
  git_rev: "v{{ version }}"

build:
  number: 0
  script: "$PYTHON -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - tox
    - twine
    - python
  run:
    - python

about:
  home: https://github.com/taskcluster/slugid.py
  license: MPL 2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: URL-safe base64 UUID encoder for generating 22 character slugs
  dev_url: https://github.com/taskcluster/slugid.py
