{% set name = "signedjson" %}
{% set version = "1.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 350586e7570ba208f7729dcda09d43f554ead0207a15e3e3695533ef3f720009

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - canonicaljson >=1.0.0
    - importlib_metadata
    - pip
    - pynacl >=0.3.0
    - python
    - typing >=3.5
    - typing_extensions >=3.5
    - unpaddedbase64 >=1.0.1
  run:
    - canonicaljson >=1.0.0
    - importlib_metadata
    - pynacl >=0.3.0
    - python
    - typing >=3.5
    - typing_extensions >=3.5
    - unpaddedbase64 >=1.0.1

test:
  imports:
    - signedjson

about:
  home: The package home page
  license: UNKNOWN
  license_family: OTHER
  license_file: 
  summary: "Sign JSON with Ed25519 signatures"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
