{% set name = "higlass-python" %}
{% set version = "0.4.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/higlass/higlass-python.git
  git_rev: "v{{ version }}"

build:
  number: 0
  script: "$PYTHON -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - clodius
    - cytoolz
    - flask
    - flask-cors
    - fusepy
    - ipywidgets>=7.5
    - matplotlib
    - multiprocess
    - requests
    - sh
    - simple-httpfs
    - slugid>=2.0.0
  run:
    - python
    - clodius
    - cytoolz
    - flask
    - flask-cors
    - fusepy
    - ipywidgets>=7.5
    - matplotlib
    - multiprocess
    - requests
    - sh
    - simple-httpfs
    - slugid>=2.0.0

about:
  home: http://github.com/higlass/higlass-python/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python bindings to and Jupyter Notebook+Lab integration for the HiGlass viewer 
  dev_url: http://github.com/higlass/higlass-python/
