{% set name = "unpaddedbase64" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

requirements:
  host:
    - pip
    - python

test:
  imports:
    - unpaddedbase64

about:
  home: https://pypi.org/project/unpaddedbase64
  license: UNKNOWN
  license_family: OTHER
  license_file: 
  summary: "Encode and decode Base64 without `=` padding"

extra:
  recipe-maintainers:
    - jrhawley
