{% set name = "msgpack" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 9534d5cc480d4aff720233411a1f765be90885750b07df772380b34c10ecb5c0

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - msgpack

about:
  home: "https://msgpack.org/"
  license: Apache Software
  license_family: APACHE
  license_file: 
  summary: "MessagePack (de)serializer."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
